param(
    [string]$Rootfs = "rootfs",
    [string]$OutFile = "docs/rootfs-package-audit.md",
    [int]$Top = 40
)

$ErrorActionPreference = "Stop"

$workspace = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$root = Join-Path $workspace $Rootfs
if (-not (Test-Path -LiteralPath $root)) {
    throw "Rootfs not found: $root"
}

$excludeFragments = @(
    "\rootfs\mnt\",
    "\rootfs\tmp\wayfire-build\",
    "\rootfs\tmp\fontconfig-cache\",
    "\rootfs\tmp\kde-home\",
    "\rootfs\tmp\kde-tmp\",
    "\rootfs\tmp\kde-var-tmp\",
    "\rootfs\tmp\wayfire-home\"
)

function Test-InExcludedPath {
    param([string]$Path)
    foreach ($fragment in $excludeFragments) {
        if ($Path.Contains($fragment)) {
            return $true
        }
    }
    return $false
}

$files = Get-ChildItem -LiteralPath $root -Recurse -Force -File -ErrorAction SilentlyContinue |
    Where-Object { -not (Test-InExcludedPath -Path $_.FullName) }

$libRootCandidates = @(
    (Join-Path $root "lib64"),
    (Join-Path $root "lib\x86_64-linux-gnu"),
    (Join-Path $root "usr\lib\x86_64-linux-gnu")
)
$libRoots = $libRootCandidates | Where-Object { Test-Path -LiteralPath $_ }

$libFiles = foreach ($libRoot in $libRoots) {
    Get-ChildItem -LiteralPath $libRoot -Recurse -Force -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like "*.so*" } |
        ForEach-Object {
            [pscustomobject]@{
                Name = $_.Name
                RelativePath = $_.FullName.Substring($root.Length + 1)
                Length = [int64]$_.Length
            }
        }
}

$duplicates = $libFiles |
    Group-Object Name |
    Where-Object { $_.Count -gt 1 } |
    Sort-Object -Property @{Expression="Count"; Descending=$true}, @{Expression="Name"; Descending=$false} |
    Select-Object -First $Top

$largest = $files |
    Sort-Object Length -Descending |
    Select-Object -First $Top

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Rootfs Package Audit")
$lines.Add("")
$lines.Add("Generated by `scripts/audit-rootfs-packages.ps1`.")
$lines.Add("")
$lines.Add("This is an audit, not a deletion list. Libraries can appear in more than one loader path intentionally.")
$lines.Add("")
$lines.Add("## Summary")
$lines.Add("")
$lines.Add("- Files scanned: $($files.Count)")
$lines.Add("- Library roots: $($libRoots.Count)")
$lines.Add("- Duplicate shared-library basenames: $($duplicates.Count)")
$lines.Add("")
$lines.Add("## Largest Files")
$lines.Add("")
$lines.Add("| MB | Path |")
$lines.Add("| ---: | --- |")
foreach ($f in $largest) {
    $rel = $f.FullName.Substring($root.Length + 1).Replace("\", "/")
    $lines.Add("| $([math]::Round(([double]$f.Length / 1MB), 2)) | ``$rel`` |")
}
$lines.Add("")
$lines.Add("## Duplicate Shared-Library Basenames")
$lines.Add("")
$lines.Add("| Count | Name | Paths |")
$lines.Add("| ---: | --- | --- |")
foreach ($g in $duplicates) {
    $paths = ($g.Group | Sort-Object RelativePath | ForEach-Object { $_.RelativePath.Replace("\", "/") }) -join "<br>"
    $lines.Add("| $($g.Count) | ``$($g.Name)`` | $paths |")
}

$outPath = Join-Path $workspace $OutFile
$outDir = Split-Path -Parent $outPath
if (-not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Path $outDir | Out-Null
}
Set-Content -LiteralPath $outPath -Value $lines -Encoding ascii
"Wrote $OutFile"
